language: node_js
node_js:
  - "0.10"
install:
  - npm install
  - npm install -g grunt-cli
  - sudo easy_install Pygments
  - 'echo "{\"VAR\": \"value\"}" > env.json'
  - 'echo "module.exports = {VALUE_FROM_JS: \"new!\"};" > env.js'
